apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: microservices-demo
  annotations:
    github.com/project-slug: fsjdevops/microservices-demo
spec:
  type: other
  lifecycle: unknown
  owner:
    projectName: online-boutique

